"""add job classification fields

Revision ID: 052eaae6874e
Revises: 180018dc4bf3
Create Date: 2026-08-27 14:01:42.007152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052eaae6874e'
down_revision: Union[str, Sequence[str], None] = '180018dc4bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

job_role_type = sa.Enum(
    'non_software',
    'frontend',
    'backend',
    'full_stack',
    'software',
    'software_engineer',
    'unknown',
    name='jobroletype',
)

resume_recommendation = sa.Enum(
    'frontend',
    'backend',
    'full_stack',
    'non_software',
    'unknown',
    name='resumerecommendation',
)


def upgrade() -> None:
    job_role_type.create(op.get_bind(), checkfirst=True)
    resume_recommendation.create(op.get_bind(), checkfirst=True)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('role_type', sa.Enum('non_software', 'frontend', 'backend', 'full_stack', 'software', 'software_engineer', 'unknown', name='jobroletype'), nullable=True))
    op.add_column('jobs', sa.Column('recommended_resume', sa.Enum('frontend', 'backend', 'full_stack', 'non_software', 'unknown', name='resumerecommendation'), nullable=True))
    op.add_column('jobs', sa.Column('is_relevant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_relevant')
    op.drop_column('jobs', 'recommended_resume')
    op.drop_column('jobs', 'role_type')
    # ### end Alembic commands ###

    resume_recommendation.drop(op.get_bind(), checkfirst=True)
    job_role_type.drop(op.get_bind(), checkfirst=True)

