"""change email job relationship to one to many

Revision ID: 180018dc4bf3
Revises: 92dc0dd5fab8
Create Date: 2026-08-24 12:30:04.036458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180018dc4bf3'
down_revision: Union[str, Sequence[str], None] = '92dc0dd5fab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobs_email_id_key'), 'jobs', type_='unique')
    op.create_index(op.f('ix_jobs_email_id'), 'jobs', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_email_id'), table_name='jobs')
    op.create_unique_constraint(op.f('jobs_email_id_key'), 'jobs', ['email_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
