"""add job fingerprint

Revision ID: 927f251c50aa
Revises: c2cb71773006
Create Date: 2026-08-12 21:56:02.318249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '927f251c50aa'
down_revision: Union[str, Sequence[str], None] = 'c2cb71773006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
    )

    op.create_index(
        "ix_jobs_fingerprint",
        "jobs",
        ["fingerprint"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_jobs_fingerprint",
        table_name="jobs",
    )

    op.drop_column(
        "jobs",
        "fingerprint",
    )
    # op.create_table('emails',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('provider', postgresql.ENUM('APPLE', 'GMAIL', 'OUTLOOK', 'YAHOO', 'OTHER', name='emailprovider'), autoincrement=False, nullable=False),
    # sa.Column('message_id', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    # sa.Column('subject', sa.VARCHAR(length=750), autoincrement=False, nullable=True),
    # sa.Column('sender', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('recipient', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('raw_body', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('is_job_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('emails_pkey'))
    # )
    # op.create_index(op.f('ix_emails_message_id'), 'emails', ['message_id'], unique=True)
    # op.create_table('jobs',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('employment_type', postgresql.ENUM('full_time', 'part_time', 'contract', 'temporary', 'intern', 'freelance', 'unknown', name='employmenttype'), autoincrement=False, nullable=True),
    # sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('salary_currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('job_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    # sa.Column('source', postgresql.ENUM('mail', 'scraper', 'api', 'manual', name='jobsource'), autoincrement=False, nullable=False),
    # sa.Column('status', postgresql.ENUM('new', 'reviewed', 'approved', 'rejected', 'applied', 'failed', 'archived', name='jobstatus'), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('work_location', postgresql.ENUM('remote', 'hybrid', 'onsite', 'unknown', name='worklocation'), autoincrement=False, nullable=True),
    # sa.Column('recruiter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('email_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('jobs_email_id_fkey')),
    # sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey')),
    # sa.UniqueConstraint('email_id', name=op.f('jobs_email_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # ### end Alembic commands ###
