"""update job and email models

Revision ID: c2cb71773006
Revises: fb42ce7aa31d
Create Date: 2026-08-06 23:05:16.645620

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cb71773006'
down_revision: Union[str, Sequence[str], None] = 'fb42ce7aa31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

work_location_enum = postgresql.ENUM(
    "remote",
    "hybrid",
    "onsite",
    "unknown",
    name="worklocation",
    # create_type=False,
)

employment_type_enum = postgresql.ENUM(
    "full_time",
    "part_time",
    "contract",
    "temporary",
    "intern",
    "freelance",
    "unknown",
    name="employmenttype",
    # create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    work_location_enum.create(bind, checkfirst=True)
    employment_type_enum.create(bind, checkfirst=True)
    # op.add_column('jobs', sa.Column('work_location', sa.Enum('remote', 'hybrid', 'onsite', 'unknown', name='worklocation'), nullable=True))
    op.add_column("jobs", sa.Column("work_location", work_location_enum,nullable=True,))
    op.add_column('jobs', sa.Column('recruiter_name', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('email_id', sa.UUID(), nullable=True))
    op.alter_column("jobs", "employment_type", existing_type=sa.VARCHAR(length=100), type_=employment_type_enum, existing_nullable=True, postgresql_using="employment_type::employmenttype",)
    # op.alter_column('jobs', 'employment_type',
    #            existing_type=sa.VARCHAR(length=100),
    #            type_=sa.Enum('full_time', 'part_time', 'contract', 'temporary', 'intern', 'freelance', 'unknown', name='employmenttype'),
    #            existing_nullable=True)
    op.create_unique_constraint(None, 'jobs', ['email_id'])
    op.create_foreign_key(None, 'jobs', 'emails', ['email_id'], ['id'])
    op.drop_column('jobs', 'remote_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.add_column('jobs', sa.Column('remote_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.alter_column('jobs', 'employment_type',
               existing_type=sa.Enum('full_time', 'part_time', 'contract', 'temporary', 'intern', 'freelance', 'unknown', name='employmenttype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('jobs', 'email_id')
    op.drop_column('jobs', 'recruiter_name')
    op.drop_column('jobs', 'work_location')
    work_location_enum.drop(bind, checkfirst=True)
    employment_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
